database: mysql
# spring:
#     jpa:
#         show-sql: true
#         generate-ddl: true
#         open-in-view: false
#         database-platform: org.hibernate.dialect.MySQL8Dialect
#         hibernate:
#             ddl-auto: update
#     datasource:
#         url: jdbc:mysql:///my_blog?cloudSqlInstance=evocative-radar-351004:asia-southeast1:loct-blog&socketFactory=com.google.cloud.sql.mysql.SocketFactory
#         username: root
#         password: Lamtanloc321@512
#         driver-class-name: com.mysql.cj.jdbc.Driver

spring:
    cloud:
        gcp:
            sql:
                database-name: my_blog
                instance-connection-name: evocative-radar-351004:asia-southeast1:loct-blog
    sql:
        init:
            mode: always  