spring:
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
